apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "chart.name" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.ingress.clusterIssuer }}
    cert-manager.io/cluster-issuer: {{ .Values.ingress.clusterIssuer }}
    {{- end }}
    {{- if .Values.ingress.externalDnsTarget }}
    external-dns.alpha.kubernetes.io/target: {{ .Values.ingress.externalDnsTarget | quote }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ . | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "chart.name" $ }}
                port:
                  number: {{ $.Values.service.port }}
    {{- end }}
  {{- with .Values.ingress.tls }}
  tls:
    - secretName: {{ .secretName }}
      hosts:
        {{- range $.Values.ingress.hosts }}
        - {{ . | quote }}
        {{- end }}
  {{- end }}
